name: CI
on:
  pull_request:
  push:
    branches: [main, staging, dev]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Lint with ruff
        run: uv run ruff check .
      - name: Type check with mypy
        run: uv run mypy .
      - name: Run tests
        run: uv run pytest
